### Users
GET http://localhost:8080/users

###
GET http://localhost:8080/users/1

###
GET http://localhost:8080/users/2
GET http://localhost:8080/users/1

### Insert
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Bob Brown",
    "email": "bob@gmail.com",
    "phone": "977557755",
    "password": "123456"
}

### Delete
DELETE http://localhost:8080/users/3

### Orders
###
GET http://localhost:8080/orders

###
GET http://localhost:8080/orders/1

###
GET http://localhost:8080/orders/2

###
GET http://localhost:8080/orders/3

### Categories
###
GET http://localhost:8080/orders

###
GET http://localhost:8080/orders/1

###
GET http://localhost:8080/orders/2

###
GET http://localhost:8080/orders/3

### Products
###
GET http://localhost:8080/products

###
GET http://localhost:8080/products/1

###
GET http://localhost:8080/products/2

###
GET http://localhost:8080/products/3

###
GET http://localhost:8080/products/4

###
GET http://localhost:8080/products/5
